on:
  push:
    branches: [v1]

jobs:
  
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
    steps:
      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@v2
        with:
          packages: cmake gcc-g++

      - uses: actions/checkout@v3
        with:
          repository: 'haproxy/haproxy'
          path: /a/HAProxy-Builds/HAProxy-Builds/haproxy

      - run: cd /cygdrive/d/a/HAProxy-Builds/HAProxy-Builds/haproxy && make TARGET=cygwin USE_REGPARM=1 USE_PCRE2=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_SLZ=1 USE_PROMEX=1

